### ISSUE TITLE
AttributeError: 'HttpClient' object has no attribute 'searchDatasets'

### ISSUE THREAD

**Issue by Philip-Wu** [kozbo/Beacon-on-GA4GH-API#2]
I'm trying out the beacon add-on for GA4GH reference server. Following the instructions I get the following error:

(flask)[root@gatkslave Beacon-on-GA4GH-API]# ./beacon.py
Traceback (most recent call last):
  File "./beacon.py", line 249, in <module>
    main()
  File "./beacon.py", line 244, in main
    fill_beacon(cl, Beacon)
  File "/srv/beacon/Beacon-on-GA4GH-API/beacon2ga4gh.py", line 196, in fill_beacon
    dataset = cl.searchDatasets().next()
AttributeError: 'HttpClient' object has no attribute 'searchDatasets'

Any suggestions?

Much obliged

**Comment by Philip-Wu** [comment]
I suspect there is a version mismatch here, but in order to get it working with the master branch i made the following changes to the code to get it working.

Change cl.searchDataSets() to cl.search_datasets()
Change cl.searchReferenceSets() to cl.search_reference_sets()

**Comment by kozbo** [comment]
Yes, that is the problem. We moved from camel case to snake case on the client library functions. I forgot to cycle back around to fix this utility. Thanks for catching it!
