### ISSUE TITLE
How to create a branch for this project

### ISSUE THREAD

**Issue by Philip-Wu** [kozbo/Beacon-on-GA4GH-API#3]
I tried to submit some fixes by creating a branch but I get forbidden response.

Can I be added as contributor?

thanks

**Comment by kozbo** [comment]
You should have contributor rights now :-)

**Comment by Philip-Wu** [comment]
Awesome thanks @kozbo 

I've committed a new branch for ga4gh-0.3.3-fixes
cheers

**Comment by Philip-Wu** [comment]
I also made a change to the way the coordinates were calculated as follows:

for foundVariant in cl.search_variants(variantSet.id, start=pos, end=pos+1, reference_name=chrom):

Here I assume consumers will provide a zero-based coordinate
